# Generated by Django 3.1.7 on 2021-04-05 01:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('content', models.TextField()),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('mood', models.IntegerField(choices=[(1, 'Happy'), (2, 'Smiling'), (3, 'Laughing'), (4, 'Lovly'), (5, 'Grumpy'), (6, 'Sad'), (7, 'Worried'), (8, 'Eyesroll'), (9, 'Sleepy'), (10, 'Crying'), (11, 'Offended'), (12, 'Amazed'), (13, 'Shocked'), (14, 'Scared'), (15, 'Hypnotized'), (16, 'Angry')])),
                ('background_img', models.ImageField(upload_to='entry/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='DiaryImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d')),
                ('diary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diary.diary')),
            ],
        ),
    ]
