# Generated by Django 3.1.7 on 2021-04-07 04:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email')),
                ('nickname', models.CharField(default='', max_length=10, unique=True, verbose_name='닉네임')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatar')),
                ('theme', models.IntegerField(blank=True, choices=[(1, 'Feb67B'), (2, 'Fe7B82'), (3, 'E6B8E9'), (4, 'Abb287'), (5, 'Bcdca0'), (6, 'E6Ccff'), (7, 'F04020'), (8, 'E0E040'), (9, 'A0Dcc0')], default=1, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_img', models.ImageField(blank=True, default='user\\image\\default.png', null=True, upload_to='profile')),
                ('theme', models.IntegerField(blank=True, choices=[(1, 'Feb67B'), (2, 'Fe7B82'), (3, 'E6B8E9'), (4, 'Abb287'), (5, 'Bcdca0'), (6, 'E6Ccff'), (7, 'F04020'), (8, 'E0E040'), (9, 'A0Dcc0')], default=1, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
