# Generated by Django 3.1.7 on 2021-04-06 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='theme',
            field=models.IntegerField(blank=True, choices=[(1, 'Feb67B'), (2, 'Fe7B82'), (3, 'E6B8E9'), (4, 'Abb287'), (5, 'Bcdca0'), (6, 'E6Ccff'), (7, 'F04020'), (8, 'E0E040'), (9, 'A0Dcc0')], null=True),
        ),
    ]
