# Generated by Django 3.1.7 on 2021-04-07 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210407_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='avatar',
            field=models.ImageField(blank=True, default='user\\image\\default.png', null=True, upload_to='avatar'),
        ),
    ]
