# Generated by Django 3.1.7 on 2021-04-06 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0002_user_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_img', models.ImageField(blank=True, default='user\\image\\default.png', null=True, upload_to='profile')),
                ('theme', models.IntegerField(blank=True, choices=[(1, 'Feb67B'), (2, 'Fe7B82'), (3, 'E6B8E9'), (4, 'Abb287'), (5, 'Bcdca0'), (6, 'E6Ccff'), (7, 'F04020'), (8, 'E0E040'), (9, 'A0Dcc0')], null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
